export enum PostHogEvent {
  PageViewed = '$pageview',
  NavigationTransition = 'navigation_transition',
  HabitCreated = 'habit_created',
  HabitUpdated = 'habit_updated',
  HabitArchived = 'habit_archived',
  HabitRestored = 'habit_restored',
  HabitLogged = 'habit_logged',
  HabitIdentityCreated = 'habit_identity_created',
  HabitIdentityUpdated = 'habit_identity_updated',
  HabitIdentityArchived = 'habit_identity_archived',
  HabitTagCreated = 'habit_tag_created',
  HabitTagDeleted = 'habit_tag_deleted',
  HabitStackCreated = 'habit_stack_created',
  HabitStackRemoved = 'habit_stack_removed',
  HabitTriggerStacksRemoved = 'habit_trigger_stacks_removed',
  HabitTreeSynced = 'habit_tree_synced',
  HabitReflectionSaved = 'habit_reflection_saved',
  HabitSettingsUpdated = 'habit_settings_updated'
}
